const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "https://media.istockphoto.com/photos/varied-food-carbohydrates-protein-vegetables-fruits-dairy-legumes-on-picture-id1218254547?b=1&k=20&m=1218254547&s=170667a&w=0&h=mOEC7x7qU5NC78mCULs-jAPeLkxy8opOvIbGSnwmAyw=",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1VMs_OUco602KFtPnZ_107c8H4rcVXry3ucsn2ugIi2a1bqKe5cjXeFy0LVIFN9U8HIs&usqp=CAU",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbVgghqFqcBxVqy1n0-thxkqbxqSueW1tQKICSfeuuAjCYrQKGpfVV44K8UfZgFXqQVhA&usqp=CAU",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3zdjjkXOOF_wItZIWEGMfmOZvsk0BP_WvcsVWSNteK-L7SOVmPuVVxeNW9e0lxGa0v94&usqp=CAU",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "https://cdn.pixabay.com/photo/2017/07/16/12/39/chicken-2509164_960_720.jpg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdzmZaAZ70E_GV8om5PWVfF5TiOpoIB4YZ-S5HfkfZCPrtjOcSnVyzE5zmumeXe5j32Xk&usqp=CAU",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpy6BzedQwdD0YMv8AICex23ZImckVS8fcjg&usqp=CAU",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "https://p4.wallpaperbetter.com/wallpaper/205/168/868/dinner-food-pie-pizza-wallpaper-preview.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjifLs0Jirp1A8w0EpV6TBLUYoVMYEd5S1AA&usqp=CAU",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
